dist: xenial
language: csharp
mono: none
dotnet: 2.2
sudo: required
script:
    - dotnet restore
    - dotnet build
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1